---
# Ignore errors using check mode
# Usage: ansible-playbook ignore_errors.yml --check
- name: Ignore errors
  hosts: managed_node1
  gather_facts: false
  vars:
    null_var: null
    empty_var: "   "
    not_empty_var: "a  "
  tasks:
    - name: Check if a variable is defined
      ansible.builtin.assert:
        that: "{{ undef_var is defined }}"
        success_msg: "undef_var is defined."
        fail_msg: "undef_var is not defined."
      # See https://ansible.readthedocs.io/projects/lint/rules/ignore-errors/
      ignore_errors: "{{ ansible_check_mode }}"

    - name: Check if a variable is null
      ansible.builtin.assert:
        that: "{{ null_var != None }}"
        success_msg: "null_var is not null."
        fail_msg: "null_var is null."
      ignore_errors: "{{ ansible_check_mode }}"

    - name: Check if a variable is empty (this method always works)
      ansible.builtin.assert:
        # Trim before checking and do not compare to an empty string
        # See https://ansible.readthedocs.io/projects/lint/rules/empty-string-compare/
        that: "{{ empty_var | trim | length != 0 }}"
        success_msg: "empty_var is not empty."
        fail_msg: "empty_var is empty."
      ignore_errors: "{{ ansible_check_mode }}"
...
# code: language=ansible
# vi: set noai nu ts=2 sw=2 sts=2 sta et:
