---
# Control loops with loop_control
# Usage: ansible-playbook control_loops.yml
- name: Control loops
  hosts: managed_node1
  gather_facts: false
  vars:
    planets:
      - planet: "Earth"
        diameter: 12756
      - planet: "Mars"
        diameter: 6792
  tasks:
    - name: Limit output
      block:
        - name: Run without loop control
          ansible.builtin.debug:
            msg: "{{ item.planet }}"
          loop: "{{ planets }}"

        - name: Run with loop control
          ansible.builtin.debug:
            msg: "{{ item.planet }}"
          loop: "{{ planets }}"
          loop_control:
            label: "{{ item.planet }}"

    - name: Pause loops
      block:
        - name: Run with loop control
          ansible.builtin.debug:
            msg: "{{ item.planet }}"
          loop: "{{ planets }}"
          loop_control:
            pause: 3
...
# code: language=ansible
# vi: set noai nu ts=2 sw=2 sts=2 sta et:
