---
# This playbook displays variable types
# Usage: ansible-playbook determine_type.yml
- name: Set and use different types of variables
  hosts: local_node
  gather_facts: false
  tasks:
    - name: Set and display a string variable
      vars:
        state_name: "Alabama"
      ansible.builtin.debug:
        var: state_name, state_name | type_debug

    - name: Set and display other types of variables
      vars:
        state_name: "Alabama"
        state_capitol: "Montgomery"
        state_number: 22
        state_number_octal: 026  # noqa yaml[octal-values]
        state_number_hex: 0x16
        percent_water: 3.39
        land_locked: false
        state_foo:
        state_bar: null
      ansible.builtin.debug:
        msg:
          - "{{ state_name }} is an {{ state_name | type_debug }} type."
          - "{{ state_capitol }} is an {{ state_capitol | type_debug }} type."
          - "{{ state_number }} is an {{ state_number | type_debug }}."
          - >-
            026 (octal {{ state_number_octal }}) is also
            an {{ state_number_octal | type_debug }}.
          - >-
            0x16 (hexadecimal {{ state_number_hex }}) is
            an {{ state_number_hex | type_debug }} as well.
          - "{{ percent_water }} is a {{ percent_water | type_debug }}."
          - "{{ land_locked }} is a {{ land_locked | type_debug }}."
          - "'{{ state_foo }}' is a {{ state_foo | type_debug }}."
          - "'{{ state_bar }}' is also a {{ state_bar | type_debug }}."
...
# code: language=ansible
# vi: set noai nu ts=2 sw=2 sts=2 sta et:
