---
# This playbook formats and transforms variables using filters
# Usage: ansible-playbook format_variables.yml
# https://jinja.palletsprojects.com/en/3.1.x/templates/#list-of-builtin-filters
# https://cplusplus.com/reference/cstdio/printf/
- name: Reformat and transform variables
  hosts: local_node
  gather_facts: false
  tasks:
    - name: Format variables using filters
      vars:
        pi: 3.1415926536
        state_number: 22
        greeting: "Hello, World!"
      ansible.builtin.debug:
        msg:
          # printf-style string formatting
          - "Scale pi ({{ pi }}) to two decimal places using the format filter: {{ '%0.2f' | format(pi) }}"
          - "Convert {{ state_number }} to hexadecimal using the format filter: {{ '0x%x' | format(state_number) }}"
          - "{{ 'Center text using the center filter' | center(50) }}"
          - "Count the chracters in '{{ greeting }}' using the length filter: {{ greeting | length }}"
          - "Round pi ({{ pi }}) to four decimal places using the round filter: {{ pi | round(4) }}"
          - "{{ state_number is boolean }}"

    - name: Transform variables using filters
      vars:
        greeting: "hello, world"
      ansible.builtin.debug:
        msg:
          - "Capitalize the first letter in '{{ greeting }}' using the capitalize filter: {{ greeting | capitalize }}"
          - "Capitalize each word in '{{ greeting }}' using the title filter: {{ greeting | title }}"
          - "Capitalize each letter in '{{ greeting }}' using the upper filter: {{ greeting | upper }}"
          - "Replace a word in '{{ greeting }}' using the replace filter: {{ greeting | replace('hello', 'Yo') }}"
          - "Spell '{{ greeting }}' backwards using the reverse filter: {{ greeting | reverse }}"
