---
# This file contains examples of the data structures used in Ansible
# Usage:
#   - ansible localhost --module-name ansible.builtin.debug --args
#       "var=f_string_1" --extra-vars "@vars.yml"
#   - ansible localhost -m debug -a "var=[f_string_2,f_string_3]" -e
#       "@vars.yml"

# Instantiate different types of scalar types
state_name: "Alabama"
state_number: 22
percent_water: 3.39
landlocked: false
state_dog: null

# Use Jinja2 templating to populate the value of a variable in a string
f_string_1: "The name of the state is {{ state_name }}."
f_string_2: "The state dog is {{ state_dog }}."

# Use nesting and indentation to denote hierarchy and scope
parent_node:
  child_node: "I belong to the parent node."
f_string_3: "The child node says, '{{ parent_node['child_node'] }}'"

# Two different ways to style a list
flow_list: [1, 2, 3]
block_list:
  - 1
  - 2
  - 3

# Two different ways to style a dictionary
flow_dict: {foo: 1, bar: 2, baz: 3}
block_dict:
  foo: 1
  bar: 2
  baz: 3

# A mixed collection of lists and dictionaries
list_of_lists_and_dicts:
  # List using flow styling
  - ["Alaska", 49, 13.77]

  # Dictionary using flow styling
  - {landlocked: false, state_dog: "Alaskan Malamute"}

  # List using block styling
  - - "Arizona"
    - 48
    - 0.3

  # Dictionary using block styling
  - landlocked: true
    state_dog: null
...
