# code: language=ansible
---
- name: Say Hello
  hosts: local_node
  gather_facts: false
  tasks:
    - name: Say Hello using Ansible's built-in debug module
      ansible.builtin.debug:
        msg:
          - "Hello, World!"
