---
# This playbook has intentional errors and styling issues
# Usage: ansible-lint perform_linting.yml
- name: run a bad play
  hosts: local_node
  gather_facts: maybe
  tasks:
    - debug:
        msg: "Hello, World!"
...
