---
# Use this playbook to demonstrate how to profile tasks
# Do not forget to enable profiling in ansible.cfg
# Usage: ansible-playbook profile_tasks.yml
- name: Profile tasks
  hosts: local_node
  gather_facts: false
  tasks:
    - name: Run a fast task
      ansible.builtin.debug:
        msg: "This is a fast task."

    - name: Run a slower task
      ansible.builtin.pause:
        seconds: "3"
        prompt: "This is a slower task."
...
