---
# This playbook runs more than one task and display multiple messages
# Usage: ansible-playbook run_multiple_tasks.yml
- name: Run multiple tasks in a play
  hosts: local_node
  gather_facts: false
  tasks:
    - name: Run a task
      ansible.builtin.debug:
        msg: "This is the first task."

    - name: Run another task
      ansible.builtin.debug:
        msg:
          - "This is the second task."
          - "This task displays two messages."
...
