---
# This playbook demonstrates how to selectively run or skip tasks
# Usage:
#   - ansible-playbook run_or_skip_tasks.yml --step
#   - ansible-playbook run_or_skip_tasks.yml --start-at-task "Run a third task"
#   - ansible-playbook run_or_skip_tasks.yml --tags odd
- name: Run or skip tasks
  hosts: local_node
  gather_facts: false
  tasks:
    - name: Run the first task
      ansible.builtin.debug:
        msg: "This is the first task."
      tags:
        - odd

    - name: Run a second task
      ansible.builtin.debug:
        msg: "This is a second task."
      tags:
        - even

    - name: Run a third task
      ansible.builtin.debug:
        msg: "This is a third task."
      tags:
        - odd

    - name: Run a fourth task
      ansible.builtin.debug:
        msg: "This is a fourth task."
      tags:
        - even
...
