---
# This playbook displays a greeting to the screen
# Usage: ansible-playbook say_hello.yml
- name: Say Hello
  hosts: local_node
  gather_facts: false
  tasks:
    - name: Say Hello
      ansible.builtin.debug:
        msg: "Hello, World!"
...
# code: language=yaml
# vi: tabstop=2 shiftwidth=2 softtabstop=2 expandtab:
