---
# This playbook demonstrates how to display a message to the screen
# Usage: ansible-playbook say_hello.yml
- name: Say Hello
  hosts: local_node
  gather_facts: false
  tasks:
    - name: Say Hello
      ansible.builtin.debug:
        msg: "Hello, World!"
...
