---
# Get and show command line variables
# Usage:
#   ansible-playbook use_cmd_line_vars.yml \
#     --extra-vars= "planet='Mars' rings=false"
- name: Use command line variables
  hosts: managed_node1
  gather_facts: false
  tasks:
    - name: Show command line variables values and types
      ansible.builtin.debug:
        msg:
          - "{{ planet }} is a {{ planet | type_debug }}."
          - "{{ rings }} is a {{ rings | type_debug }}."
...
# code: language=ansible
# vi: set noai nu ts=2 sw=2 sts=2 sta et:
