---
# Gather and show special variables and facts
# Usage: ansible-playbook use_special_vars.yml
- name: Use special variables
  hosts: managed_node1
  gather_facts: false
  tasks:
    - name: Show default magic variables
      ansible.builtin.debug:
        msg: "{{ hostvars }}"

    - name: Show a magic variable
      ansible.builtin.debug:
        msg: "{{ inventory_hostname }}"

    - name: Scan the target node and gather facts
      ansible.builtin.setup:

    - name: Show gathered magic variables and facts
      ansible.builtin.debug:
        msg: "{{ hostvars }}"

    - name: Show facts for the target node only
      ansible.builtin.debug:
        msg: "{{ ansible_facts }}"

    - name: Show a fact
      ansible.builtin.debug:
        msg: "{{ ansible_facts['os_family'] }}"

- name: Gather facts by default
  hosts: managed_node1
  gather_facts: true
  tasks:
    # Results should be the same as the last three tasks
    # of the previous play
    - name: Show gathered magic variables and facts
      ansible.builtin.debug:
        msg: "{{ hostvars }}"

    - name: Show facts for the target node only
      ansible.builtin.debug:
        msg: "{{ ansible_facts }}"

    - name: Show a fact about the target node
      ansible.builtin.debug:
        msg: "{{ ansible_facts['os_family'] }}"
...
# code: language=ansible
# vi: set noai nu ts=2 sw=2 sts=2 sta et:
