---
# Reusable list of tasks
# Usage:
# ansible.builtin.import_tasks:
#   file: sub_tasks.yml
# ansible.builtin.include_tasks:
#   file: sub_tasks.yml
- name: Show another message
  ansible.builtin.debug:
    msg:
      - "I am an external task."
      - "{{ item | default('Earth') }} is a planet."
...
# code: language=ansible
# vi: set noai nu ts=2 sw=2 sts=2 sta et:
