---
# Access data in YAML files
# Usage: ansible-playbook include_files.yml
- name: Include files
  hosts: managed_node1
  gather_facts: false
  tasks:
    - name: Include a YAML file in a play
      ansible.builtin.include_vars:
        file: planets.yml

    - name: Access data from the YAML file
      ansible.builtin.debug:
        msg:
          - "Planet info: {{ planets[3] }}"
          - "Planet name: {{ planets[3]['planet'] }}"
...
# code: language=ansible
# vi: set noai nu ts=2 sw=2 sts=2 sta et:
