---
# This playbook checks if values are identical
# Usage: ansible-playbook check_identity.yml
- name: Check if values are identical
  hosts: managed_node1
  gather_facts: false
  tasks:
    - name: Check if values are identical
      ansible.builtin.debug:
        msg:
          # 1 is an integer, not a boolean, so this is false
          - "1 is true: {{ 1 is true }}"
          - "true is true: {{ true is true }}"
          # 'is' has a higher precedence than '==' (i.e., 1 == (1 is true)),
          # so '1 is true', which is 'false', is not an integer or '1'
          - "This is bad code: 1 == 1 is true: {{ 1 == 1 is true }}"
          # Parenthesis have a higher precedence than 'is'
          - "This is good code: (1 == 1) is true: {{ (1 == 1) is true }}"
          - "This is good code: (1 == 1) is false: {{ (1 == 1) is false }}"

    - name: Check if values are not identical
      ansible.builtin.debug:
        msg:
          - "1 is not true: {{ 1 is not true }}"
          - "true is not true: {{ true is not true }}"
          - "This is bad code: 1 == 1 is not true: {{ 1 == 1 is not true }}"
          - "This is good code: (1 == 1) is not true: {{ (1 == 1) is not true }}"
          - "This is good code: (1 == 1) is not false: {{ (1 == 1) is not false }}"

    - name: Check value identity using tests
      # https://jinja.palletsprojects.com/en/3.1.x/templates/#list-of-builtin-tests
      ansible.builtin.debug:
        msg:
          - "1 is a number: {{ 1 is number }}"
          - "1 is an integer: {{ 1 is integer }}"
          - "1 is a float: {{ 1 is float }}"
          - "1 is a boolean: {{ 1 is boolean }}"
...
# code: language=ansible
# vi: set noai nu ts=2 sw=2 sts=2 sta et:
