---
# This playbook formats and transforms variables using filters
# https://jinja.palletsprojects.com/en/3.1.x/templates/#list-of-builtin-filters
# https://cplusplus.com/reference/cstdio/printf/
# Usage: ansible-playbook format_variables.yml
- name: Reformat and transform variables
  hosts: managed_node1
  gather_facts: false
  tasks:
    - name: Format variables using filters
      vars:
        pi: 3.1415926536
        degrees: 360
      ansible.builtin.debug:
        msg:
          # printf-style formatting
          - "{{ pi }}: {{ '%0.2f' | format(pi) }}"
          - "{{ degrees }}: {{ '%x' | format(degrees) }}"
          # New style formatting
          - "{{ pi }}: {{ '{:.2f}'.format(pi) }}"
          - "{{ degrees }}: {{ '{:#x}'.format(degrees) }}"

    - name: Transform variables using filters
      vars:
        greeting: "hello, world"
      ansible.builtin.debug:
        msg:
          - "Original: {{ greeting }}"
          - "Sentence Case: {{ greeting | capitalize }}"
          - "Title Case: {{ greeting | title }}"
          - "Uppercase: {{ greeting | upper }}"
          - >-
            Replace Word:
            {{ greeting | replace('hello', 'Yo') }}
          - "Reverse Characters: {{ greeting | reverse }}"
          - "Center: {{ greeting | center(40) }}"
          - "Length: {{ greeting | length }} characters."
...
# code: language=ansible
# vi: set noai nu ts=2 sw=2 sts=2 sta et:
