---
# This playbook gets and displays special variables and facts
# Usage: ansible-playbook get_special_vars.yml
- name: Display magic variables and gathered facts
  hosts: managed_node1
  gather_facts: false
  tasks:
    - name: Display magic variables Ansible always collects
      ansible.builtin.debug:
        msg: "{{ hostvars }}"

    - name: Display a magic variable
      ansible.builtin.debug:
        msg: "{{ inventory_hostname }}"

    - name: Scan the target node and gather facts
      ansible.builtin.setup:

    - name: Display all magic variables and facts
      ansible.builtin.debug:
        msg: "{{ hostvars }}"

    - name: Display facts for the target node only
      ansible.builtin.debug:
        msg: "{{ ansible_facts }}"

    - name: Display a fact about the target node
      ansible.builtin.debug:
        msg: "{{ ansible_facts['os_family'] }}"

- name: Gather facts by default
  hosts: managed_node1
  gather_facts: true
  tasks:
    # Results should be the same as the last three tasks
    # of the previous play
    - name: Display all magic variables and facts
      ansible.builtin.debug:
        msg: "{{ hostvars }}"

    - name: Display facts for the target node only
      ansible.builtin.debug:
        msg: "{{ ansible_facts }}"

    - name: Display a fact about the target node
      ansible.builtin.debug:
        msg: "{{ ansible_facts['os_family'] }}"
...
# code: language=ansible
# vi: set noai nu ts=2 sw=2 sts=2 sta et:
