---
# This playbook captures and displays the return values of a task
# Usage: ansible-playbook get_return_values.yml
- name: Capture and display the return values of a task
  hosts: managed_node_1
  gather_facts: false
  tasks:
    - name: Say Hello
      ansible.builtin.debug:
        msg: "Hello, World!"
      register: result

    - name: Display the return values of the previous task
      ansible.builtin.debug:
        var: result

    - name: Display a single return value
      ansible.builtin.debug:
        var: "result['failed']"
...
# code: language=ansible
# vi: set noai nu ts=2 sw=2 sts=2 sta et:
