---
# This playbook groups tasks using blocks and tags
# Usage:
# - ansible-playbook group_tasks.yml
# - ansible-playbook group_tasks.yml --tags foo
# - ansible-playbook group_tasks.yml --skip-tags foo
- name: Group tasks using blocks
  hosts: managed_node1
  gather_facts: false
  tasks:
    - name: Create a block of foo tasks
      tags:
        - foo
      block:
        - name: Run a foo task
          ansible.builtin.debug:
            msg: "This is a foo task."

        - name: Run another foo task
          ansible.builtin.debug:
            msg: "This is another foo task."

    - name: Create a block of bar tasks
      tags:
        - bar
      block:
        - name: Run a bar task
          ansible.builtin.debug:
            msg: "This is a bar task."

        - name: Run another bar task
          ansible.builtin.debug:
            msg: "This is another bar task."
...
# code: language=ansible
# vi: set noai nu ts=2 sw=2 sts=2 sta et:
