---
# Ansible inventory using YAML format
all:
  hosts:
    local_node:
      ansible_connection: local

  children:
    control_node:
      hosts:
        local_node:

    managed_nodes:
      hosts:
        local_node:
...
# code: language=yaml
# vi: set noai nu ts=2 sw=2 sts=2 sta et:
