---
# Use this playbook to log the output of a play
# Do not forget to enable logging in ansible.cfg
# Usage:
#   - ansible-playbook log_output.yml
#   - ansible-playbook log_output.yml -v
- name: Log output
  hosts: local_node
  gather_facts: false
  tasks:
    - name: Run the first task
      ansible.builtin.debug:
        msg: "This is the first task."

    - name: Run a secret task
      ansible.builtin.debug:
        msg: "The super-secret squirrel password is 'qwerty'!"
      no_log: true

    - name: Run the last task
      ansible.builtin.debug:
        msg: "This is the last task."
...
# code: language=ansible
# vi: set noai nu ts=2 sw=2 sts=2 sta et:
