---
# This playbook has intentional errors and styling issues
# Usage: ansible-lint perform_linting.yml
- name: run a bad play
  hosts: local_node
  gather_facts: maybe
  tasks:
    - debug:
        msg: "Hello, World!"
  ignore_errors: true # noqa ignore-errors
...
# code: language=ansible
# vi: set noai nu ts=2 sw=2 sts=2 sta et:
