---
# Use this playbook to profile tasks for time
# Do not forget to enable profiling in ansible.cfg
# Usage: ansible-playbook profile_tasks.yml
- name: Profile tasks
  hosts: managed_node1
  gather_facts: false
  tasks:
    - name: Run a fast task
      ansible.builtin.debug:
        msg: "This is a fast task."

    - name: Run a slower task
      ansible.builtin.pause:
        seconds: "3"
        prompt: "This is a slower task."
...
# code: language=ansible
# vi: set noai nu ts=2 sw=2 sts=2 sta et:
