---
# Use this playbook to selectively run or skip tasks
# Usage:
# - ansible-playbook run_or_skip_tasks.yml --step
# - ansible-playbook run_or_skip_tasks.yml --start-at-task "Run a third task"
# - ansible-playbook run_or_skip_tasks.yml --tags odd
# - ansible-playbook run_or_skip_tasks.yml --skip-tags odd
- name: Run or skip tasks
  hosts: managed_node_1
  gather_facts: false
  tasks:
    - name: Run the first task
      tags:
        - odd
      ansible.builtin.debug:
        msg: "This is the first task."

    - name: Run a second task
      tags:
        - even
      ansible.builtin.debug:
        msg: "This is a second task."

    - name: Run a third task
      tags:
        - odd
      ansible.builtin.debug:
        msg: "This is a third task."

    - name: Run a fourth task
      tags:
        - even
      ansible.builtin.debug:
        msg: "This is a fourth task."
...
# code: language=ansible
# vi: set noai nu ts=2 sw=2 sts=2 sta et:
