---
# This playbook runs more than one play
# Usage: ansible-playbook run_multiple_plays.yml
- name: Run a play
  hosts: local_node
  gather_facts: false
  tasks:
    - name: Display a message in the first play
      ansible.builtin.debug:
        msg: "This is the first play."

- name: Run another play in the same playbook
  hosts: local_node
  gather_facts: false
  tasks:
    - name: Display a message in the second play
      ansible.builtin.debug:
        msg: "This is the second play."
...
# code: language=ansible
# vi: set noai nu ts=2 sw=2 sts=2 sta et:
