---
# This playbook displays a greeting on the screen
# Usage: ansible-playbook say_hello.yml
- name: Say Hello
  hosts: managed_node_1
  gather_facts: false
  tasks:
    - name: Say Hello
      ansible.builtin.debug:
        msg: "Hello, World!"
...
# code: language=ansible
# vi: set noai nu ts=2 sw=2 sts=2 sta et:
