---
# This playbook splits up long strings to improve readability
# Usage: ansible-playbook split_strings.yml
- name: Split up long strings
  hosts: managed_node1
  gather_facts: false
  tasks:
    - name: Use flow styling to display output (default)
      ansible.builtin.debug:
        msg: "Happy Birthday to You, Happy Birthday to You, Happy Birthday, Happy Birthday, Happy Birthday to You!"

    - name: Use a literal block scalar
      # Use a literal block scalar (|) to preserve newlines in a multiline string
      ansible.builtin.debug:
        msg: |
          Happy Birthday to You,
          Happy Birthday to You,
          Happy Birthday, Happy Birthday,
          Happy Birthday to You!

    - name: Use a folded block scalar
      # Use a folded block scalar (>) to collapse a multiline string into a single line
      ansible.builtin.debug:
        msg: >
          Happy Birthday to You,
          Happy Birthday to You,
          Happy Birthday, Happy Birthday,
          Happy Birthday to You!

    - name: Use a literal block scalar with chomping
      # Use a literal block scalar (|-), but explicitly chomp the final newline
      ansible.builtin.debug:
        msg: |-
          Happy Birthday to You,
          Happy Birthday to You,
          Happy Birthday, Happy Birthday,
          Happy Birthday to You!

    - name: Use a folded block scalar with chomping
      # Use a folded block scalar (>-) with chomping (same as the default result)
      ansible.builtin.debug:
        msg: >-
          Happy Birthday to You,
          Happy Birthday to You,
          Happy Birthday, Happy Birthday,
          Happy Birthday to You!
...
# code: language=ansible
# vi: set noai nu ts=2 sw=2 sts=2 sta et:
