---
# This playbook sets and uses dictionaries of variables
# Usage: ansible-playbook use_dicts.yml
- name: Set and use dictionaries of variables
  hosts: managed_node_1
  gather_facts: false
  tasks:
    - name: Set and display a dictionary
      vars:
        mars:
          planet_name: "Mars"
          diameter: 6792
          hours_in_day: 24.7
          rings: false
      ansible.builtin.debug:
        msg:
          - "{{ mars }}"
          - >-
            {{ mars['planet_name'] }} is
            {{ mars.diameter }} km in diameter.
          - >-
            One day on {{ mars['planet_name'] }} is
            {{ mars['hours_in_day'] }} Earth hours.
          - "Rings: {{ mars['rings'] }}"
...
# code: language=ansible
# vi: set noai nu ts=2 sw=2 sts=2 sta et:
