---
# This playbook uses dictionaries
# Usage: ansible-playbook use_dicts.yml
- name: Use dictionaries
  hosts: managed_node_1
  gather_facts: false
  tasks:
    - name: Set and display a dictionary
      vars:
        jupiter:
          planet_name: "Jupiter"
          diameter_dec: 142984
          hours_per_day: 9.9
          rings: true
      ansible.builtin.debug:
        msg:
          - "{{ jupiter }}"
          - >-
            {{ jupiter['planet_name'] }} is
            {{ jupiter.diameter_dec }} km in diameter.
          - >-
            One day on {{ jupiter['planet_name'] }} is
            {{ jupiter['hours_per_day'] }} Earth hours.
          - "Rings: {{ jupiter['rings'] }}"
...
# code: language=ansible
# vi: set noai nu ts=2 sw=2 sts=2 sta et:
