---
# This playbook uses a default value if a variable is undefined
# Usage: ansible-playbook use_default_value.yml
- name: Use default values
  hosts: managed_node1
  gather_facts: false
  vars:
    defined_var: "This variable is defined."
    empty_var: ""
  tasks:
    - name: Display a defined variable
      ansible.builtin.debug:
        msg: "{{ defined_var }}"

    - name: Display an undefined variable
      block:
        - name: Attempt to display an undefined variable
          ansible.builtin.debug:
            msg: "{{ undefined_var }}"

      rescue:
        - name: >-
            Display a default value for an undefined variable
          ansible.builtin.debug:
            msg: >-
              {{ undefined_var | default('I am undefined!') }}

    - name: Display an empty variable
      ansible.builtin.debug:
        msg: "{{ empty_var | default('I am empty!') }}"

    - name: Display a default value for an empty variable
      ansible.builtin.debug:
        msg: "{{ empty_var | default('I am empty!', true) }}"
...
# code: language=ansible
# vi: set noai nu ts=2 sw=2 sts=2 sta et:
