---
# This playbook uses different types of scalar variables
# Usage: ansible-playbook use_variables.yml
- name: Use different types of scalar variables
  hosts: managed_node_1
  gather_facts: false
  tasks:
    - name: Set and display a string variable
      vars:
        # Use quotation marks to explicitly declare strings
        planet_name: "Mercury"
      ansible.builtin.debug:
        var: planet_name

    - name: Set and display other scalar variables
      vars:
        planet_name: "Mercury"
        diameter: 4879
        diam_hex: 0x130F
        diam_oct: 011417 # noqa yaml[octal-values]
        hours_in_day: 4222.6
        # Use 'true/false' instead of 'yes/no' or 'on/off'
        rings: false
        # Leave blank or use 'null' for NoneType
        moons: null
      ansible.builtin.debug:
        msg:
          - "The name of the planet is {{ planet_name }}."
          - "It is {{ diameter }} km in diameter."
          - "0x130F (hex) = {{ diam_hex }} (dec)."
          - "011417 (oct) = {{ diam_oct }} (dec)."
          - >-
            One day on {{ planet_name }} is
            {{ hours_in_day }} Earth hours.
          - "Rings: {{ rings }}"
          - "Moons: {{ moons }}"
...
# code: language=ansible
# vi: set noai nu ts=2 sw=2 sts=2 sta et:
