---
# This playbook uses lists of variables
# Usage: ansible-playbook use_lists.yml
- name: Use lists of variables
  hosts: managed_node_1
  gather_facts: false
  tasks:
    - name: Set and display a list
      vars:
        major_moons:
          - "Ganymede"
          - "Callisto"
          - "Europa"
          - "Io"
      ansible.builtin.debug:
        msg:
          - "{{ major_moons }}"
          - >-
            {{ major_moons[0] }} is bigger than
            {{ major_moons.2 }}.

    - name: Set and display a mixed list
      vars:
        jupiter:
          - "Jupiter"
          - 142984
          - 9.9
          - true
      ansible.builtin.debug:
        msg:
          - "{{ jupiter }}"
          - >-
            {{ jupiter[0] }} is {{ jupiter[1] }} km
            in diameter.
          - >-
            One day on {{ jupiter[0] }} is
            {{ jupiter[2] }} Earth hours.
          - "Rings: {{ jupiter[3] }}"
...
# code: language=ansible
# vi: set noai nu ts=2 sw=2 sts=2 sta et:
