---
# This file demos different data types used by Ansible
# Usage: ansible localhost --module-name ansible.builtin.debug --args "var=continent_name" --extra-vars "@vars.yml"

# Different types of scalar variables
continent_name: "Antarctica"
geo_rank: 5
geo_pct: 9.5
connected: false
countries: null

# Two different ways to style a list of values
# Use nesting and indentation to denote hierarchy and scope
flow_list: ["Antarctica", 5, 9.5]
block_list:
  - "Antarctica"
  - 5
  - 9.5

# Two different ways to style a dictionary of variables
flow_dict: { connected: false, countries: null }
block_dict:
  connected: false
  countries: null

# A list of lists and dictionaries
list_of_lists_and_dicts:
  - ["Antarctica", 5, 9.5]
  - { connected: false, countries: null }
  - - "Antarctica"
    - 5
    - 9.5
  - connected: false
    countries: null
...
# code: language=yaml
# vi: set noai nu ts=2 sw=2 sts=2 sta et:
