# This playbook runs the plays and tasks in the playbooks
# Usage: ansible-playbook playbooks/x_all_plays.yml
---
# Usage: ansible-playbook say_hello.yml
- name: Say Hello
  hosts: managed_node_1
  gather_facts: false
  tasks:
    - name: Say Hello
      ansible.builtin.debug:
        msg: "Hello, World!"

# Usage: ansible-playbook run_multiple_tasks.yml
- name: Run multiple tasks in a play
  hosts: managed_node_1
  gather_facts: false
  tasks:
    - name: Run a task
      ansible.builtin.debug:
        msg: "This is the first task."

    - name: Run another task
      ansible.builtin.debug:
        msg: "This is the second task."

# Usage: ansible-playbook run_multiple_plays.yml
- name: Run a play
  hosts: managed_node_1
  gather_facts: false
  tasks:
    - name: Display a message in the first play
      ansible.builtin.debug:
        msg: "This is the first play."

- name: Run another play in the same playbook
  hosts: managed_node_1
  gather_facts: false
  tasks:
    - name: Display a message in the second play
      ansible.builtin.debug:
        msg: "This is the second play."

# Usage: ansible-playbook breakup_strings.yml
- name: Break up long strings
  hosts: managed_node_1
  gather_facts: false
  tasks:
    - name: Use flow styling to display output (default)
      ansible.builtin.debug:
        msg: "Happy Birthday to You, Happy Birthday to You, Happy Birthday, Happy Birthday, Happy Birthday to You!"

    - name: Use a literal block scalar (|) to preserve newlines in a multiline string
      ansible.builtin.debug:
        msg: |
          Happy Birthday to You,
          Happy Birthday to You,
          Happy Birthday, Happy Birthday,
          Happy Birthday to You!

    - name: Use a folded block scalar (>) to collapse a multiline string into a single line
      ansible.builtin.debug:
        msg: >
          Happy Birthday to You,
          Happy Birthday to You,
          Happy Birthday, Happy Birthday,
          Happy Birthday to You!

    - name: Use a literal block scalar (|-), but explicitly chomp the final newline
      ansible.builtin.debug:
        msg: |-
          Happy Birthday to You,
          Happy Birthday to You,
          Happy Birthday, Happy Birthday,
          Happy Birthday to You!

    - name: Use a folded block scalar (>-) with chomping (same as the default result)
      ansible.builtin.debug:
        msg: >-
          Happy Birthday to You,
          Happy Birthday to You,
          Happy Birthday, Happy Birthday,
          Happy Birthday to You!

# Usage:
# - ansible-playbook run_or_skip_tasks.yml --step
# - ansible-playbook run_or_skip_tasks.yml --start-at-task "Run a third task"
# - ansible-playbook run_or_skip_tasks.yml --tags odd
# - ansible-playbook run_or_skip_tasks.yml --skip-tags odd
- name: Run or skip tasks
  hosts: managed_node_1
  gather_facts: false
  tasks:
    - name: Run the first task
      tags:
        - odd
      ansible.builtin.debug:
        msg: "This is the first task."

    - name: Run a second task
      tags:
        - even
      ansible.builtin.debug:
        msg: "This is a second task."

    - name: Run a third task
      tags:
        - odd
      ansible.builtin.debug:
        msg: "This is a third task."

    - name: Run a fourth task
      tags:
        - even
      ansible.builtin.debug:
        msg: "This is a fourth task."

# Usage:
# - ansible-playbook organize_tasks.yml
# - ansible-playbook organize_tasks.yml --tags foo
# - ansible-playbook organize_tasks.yml --skip-tags foo
- name: Organize tasks using blocks
  hosts: managed_node_1
  gather_facts: false
  tasks:
    - name: Create a block of foo tasks
      tags:
        - foo
      block:
        - name: Run a foo task
          ansible.builtin.debug:
            msg: "This is a foo task."

        - name: Run another foo task
          ansible.builtin.debug:
            msg: "This is another foo task."

    - name: Create a block of bar tasks
      tags:
        - bar
      block:
        - name: Run a bar task
          ansible.builtin.debug:
            msg: "This is a bar task."

        - name: Run another bar task
          ansible.builtin.debug:
            msg: "This is another bar task."

# Usage: ansible-playbook handle_errors.yml
- name: Perform error handling
  hosts: managed_node_1
  gather_facts: false
  tasks:
    - name: Perform error handling
      block:
        - name: Perform a task that passes
          ansible.builtin.debug:
            msg: "I passed!"

        - name: Perform a tasks that fails
          ansible.builtin.fail:
            msg: "I failed."

        - name: Create a task that will not run
          ansible.builtin.debug:
            msg: "I will not run, since the previous task failed."
      rescue:
        - name: Display an error message
          ansible.builtin.debug:
            msg: "I run if a task in the block fails."
      always:
        - name: Perform a task whether the previous tasks passed or failed
          ansible.builtin.debug:
            msg: "I always run."

    # Usage: ansible-playbook use_variables.yml
    - name: Use different types of scalar variables
      hosts: managed_node_1
      gather_facts: false
      tasks:
        - name: Set and display a string variable
          vars:
            # Use quotation marks to explicitly declare strings
            planet_name: "Mercury"
          ansible.builtin.debug:
            var: planet_name

        - name: Set and display other scalar variables
          vars:
            planet_name: "Mercury"
            diameter_dec: 4879
            diameter_hex: 0x130F
            diameter_oct: 011417 # noqa yaml[octal-values]
            hours_per_day: 4222.6
            # Use 'true/false' instead of 'yes/no' or 'on/off'
            rings: false
            # Leave blank or use 'null' for NoneType
            major_moons: null
          ansible.builtin.debug:
            msg:
              - "The name of the planet is {{ planet_name }}."
              - "It is {{ diameter_dec }} kilometers in diameter."
              - "0x130F (hexadecimal) = {{ diameter_hex }} (dec)."
              - "011417 (octal) = {{ diameter_oct }} (dec)."
              - >-
                One day on {{ planet_name }} is
                {{ hours_per_day }} Earth hours.
              - "Rings: {{ rings }}"
              - "Moons: {{ major_moons }}"

    # Usage: ansible-playbook use_lists.yml
    - name: Use lists of variables
      hosts: managed_node_1
      gather_facts: false
      tasks:
        - name: Set and display a list
          vars:
            major_moons:
              - "Ganymede"
              - "Callisto"
              - "Europa"
              - "Io"
          ansible.builtin.debug:
            msg:
              - "{{ major_moons }}"
              - >-
                {{ major_moons[0] }} is bigger than
                {{ major_moons.2 }}.

        - name: Set and display a mixed list
          vars:
            jupiter:
              - "Jupiter"
              - 142984
              - 9.9
              - true
          ansible.builtin.debug:
            msg:
              - "{{ jupiter }}"
              - >-
                {{ jupiter[0] }} is {{ jupiter[1] }} km
                in diameter.
              - >-
                One day on {{ jupiter[0] }} is
                {{ jupiter[2] }} Earth hours.
              - "Rings: {{ jupiter[3] }}"

    # Usage: ansible-playbook use_dicts.yml
    - name: Use dictionaries
      hosts: managed_node_1
      gather_facts: false
      tasks:
        - name: Set and display a dictionary
          vars:
            jupiter:
              planet_name: "Jupiter"
              diameter_dec: 142984
              hours_per_day: 9.9
              rings: true
          ansible.builtin.debug:
            msg:
              - "{{ jupiter }}"
              - >-
                {{ jupiter['planet_name'] }} is
                {{ jupiter.diameter_dec }} km in diameter.
              - >-
                One day on {{ jupiter['planet_name'] }} is
                {{ jupiter['hours_per_day'] }} Earth hours.
              - "Rings: {{ jupiter['rings'] }}"
...
# code: language=ansible
# vi: set noai nu ts=2 sw=2 sts=2 sta et:
