---
# Uses conditionals to run a task
# Usage: ansible-playbook use_conditionals.yml
- name: Use conditionals
  hosts: managed_node1
  gather_facts: false
  vars:
    planet: "Mars"
    rocky:
      - Mercury
      - Venus
      - Earth
      - Mars
  tasks:
    - name: Show message based on a condition (if)
      ansible.builtin.debug:
        msg:
          - "{{ 'Mars' if planet == 'Mars' }}"
          - "{{ 'Rocky' if 'Mars' in rocky }}"

    - name: Show alternate message (if-else)
      ansible.builtin.debug:
        msg:
          - "{{ 'Mars' if planet == 'Mars' else 'Earth' }}"
          - "{{ 'Rocky' if 'Mars' in rocky else 'Gas' }}"

    - name: Show alternate message (ternary filter)
      ansible.builtin.debug:
        msg:
          - >-
            {{ (planet == 'Mars') is true | ternary('Mars',
            'Earth') }}
          - >-
            {{ ('Mars' in rocky) is false | ternary('Gas',
            'Rocky') }}

    - name: Perform a task if a condition is met (when)
      ansible.builtin.debug:
        msg: "Welcome to Mars!"
      when: planet == 'Mars'

    - name: Skip a task if a condition is not met (when)
      ansible.builtin.debug:
        msg: "Mars is a gas giant."
      when: "'Mars' not in rocky"
...
# code: language=ansible
# vi: set noai nu ts=2 sw=2 sts=2 sta et:
